spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: NutriLedgerPool
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: off
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  jackson:
    property-naming-strategy: SNAKE_CASE
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GCLOUD_CLIENT_ID}
            client-secret: ${GCLOUD_CLIENT_SECRET}
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: ${GCLOUD_AUTH_URI}
            token-uri: ${GCLOUD_TOKEN_URI}
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub
